apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q22r3vccc-go
  janus-idp.io/tekton: q22r3vccc-go
  backstage.io/kubernetes-id: q22r3vccc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q22r3vccc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
