apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q22r3vccc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q22r3vccc-go 
  name: q22r3vccc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q22r3vccc-go 
